### ISSUE TITLE
help on filtering policies

### ISSUE THREAD

**Issue by zephyr2k7** [vladimirs-git/fortigate-api#1]
Hi,
Regarding the policy filters how can I try to get all policies filtered by destination address?
For example to extract all policies that allora traffic to a specific il say 192.168.1.2?

Thanks in advance for your help

**Comment by vladimirs-git** [comment]
```python
from fortigate_api.api import FortigateAPI

fgt = FortigateAPI(host="host", username="username", password="password")

subnet = "192.168.1.2 255.255.255.255"
addresses = fgt.address.get(filters=[f"subnet=={subnet}", "type==ipmask"])
for address in addresses:
    dstaddr = address["name"]
    policies = fgt.policy.get(filter=f"dstaddr=={dstaddr}")
    for policy in policies:
        print(policy)
```

**Comment by zephyr2k7** [comment]
thankyou very much

**Comment by vladimirs-git** [comment]
since version 0.2.1 you can use extended filter to filter rules much easier
`
from pprint import pprint
from fortigate_api import FortigateAPI

fgt = FortigateAPI(host="host", username="username", password="password")
fgt.login()
policies = fgt.policy.get(efilter="srcaddr<=192.168.0/24")
pprint(policies)
`
